### ISSUE TITLE
BlockStatementMutator mutant seems to be reported with an extra character

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-html-reporter#5]
See https://github.com/stryker-mutator/stryker/issues/153

**Comment by simondel** [comment]
[The event-recorder reporter the following info on my machine](https://github.com/stryker-mutator/stryker-html-reporter/files/504518/stryker-events-153.zip)

**Comment by nicojs** [comment]
@bkimminich we just did a new release of the stryker-html-reporter (v0.2.2). Can you confirm that this is fixed?

**Comment by bkimminich** [comment]
I did `npm update` and definitely got the 0.2.2 but [this](https://github.com/stryker-mutator/stryker/issues/153) ist still happening:

![image](https://cloud.githubusercontent.com/assets/3531020/19151190/a1c8d94a-8bcb-11e6-8cf2-3d7a4f74937d.png)

**Comment by simondel** [comment]
Well, that actually looks good because we haven't changed the `BlockStatementMutator` yet to ignore empty blocks ;)

**Comment by bkimminich** [comment]
Ah', so the fact that I removed the useless `'use strict'` bit me... :-)
